import MainHeader from "../../components/main-header/MainHeader";
import Footer from "../../components/Footer/Footer";
import AsideBar from "../../components/asideBar/AsideBar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        <div style={{ display: "flex", flexDirection: "row" }}>
          <AsideBar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
